#:schema node_modules/wrangler/config-schema.json
name = "twikoo-cloudflare"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "641115ac-d857-47f0-a61b-8ba9d21bceab"

[[r2_buckets]]
binding = "R2"
bucket_name = "twikoo"

[vars]
R2_PUBLIC_URL = ""

[dev]
port = 5000
#强制部署
